"""add nickname in user

Revision ID: 8c8c699dc8d5
Revises: 21e20083868e
Create Date: 2018-04-14 21:44:30.620433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8c699dc8d5'
down_revision = '21e20083868e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
